name: CICD
on:
  push:
    paths-ignore:
      - README.md
      - LICENSE
      - images
      - terraform
      - azure-pipeline.yml
      
env:
  DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
  DATABRICKS_TOKEN:  ${{ secrets.DATABRICKS_TOKEN }}
  REPO_DIRECTORY: ${{ vars.REPO_DIRECTORY }}
  CLUSTER_ID: ${{ vars.CLUSTER_ID }}
  TEST_DLT_PIPELINE_ID: 752345209143482
  TEST_DLT_PIPELINE_NAME: "Demo Integration Test"

permissions:
  checks: write
jobs:
  OnPush:
    if: ${{ !(startsWith(github.ref_name, 'releases')) && !(startsWith(github.ref_name, 'tags')) }} 
    environment: dev
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
      
    - name: Install libraries
      run: |
        pip install --upgrade pip nutter poetry
    - name: Update databricks repo
      run: |
        databricks repos update --path $REPO_DIRECTORY --branch "${{github.ref_name}}"
      
    - name: Run Tests
      run: |
        nutter run "$REPO_DIRECTORY/tests/unit-tests/" --cluster_id $CLUSTER_ID --recursive --junit_report --timeout 500

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: success() || failure() # always run even if the previous step fails
      with:
        report_paths: '**/test-*.xml'

  CheckRef:
    runs-on: ubuntu-latest
    steps:
    - name: Check Ref
    run: |
     {{ $github.ref_name }}
     
  OnRelease:
    if: startsWith(github.ref_name, 'releases')
    environment: stage
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install libraries
      run: |
        pip install --upgrade pip nutter
    - name: install-databricks-cli
      uses: microsoft/install-databricks-cli@v1.0.0

    - name: Update databricks repo
      run: |
        databricks repos update --path $REPO_DIRECTORY --branch "${{github.ref_name}}"
    - name: Run Tests
      run: |
        pwd
        nutter run "$REPO_DIRECTORY/tests/unit-tests/" --cluster_id $CLUSTER_ID --recursive --junit_report --timeout 500
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: success() || failure() # always run even if the previous step fails
      with:
        report_paths: '**/test-*.xml'  
        
  DeployProduction:
    environment: prod
    runs-on: ubuntu-latest
    needs: [OnRelease]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install libraries
      run: |
        pip install --upgrade pip nutter
    - name: install-databricks-cli
      uses: microsoft/install-databricks-cli@v1.0.0

    - name: Update databricks repo
      run: |
        databricks repos update --path $REPO_DIRECTORY --branch "${{github.ref_name}}"
